//Task No 22


const Intensionally_error_Array: number[] = [1, 2, 3];
const index = 5;

try{
    console.log(Intensionally_error_Array[index]);
}
catch{
    console.log("Error Occured");
}

